[package]
name = "nexus-control"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/Vitrixxl/nexus"
description = "A quiet control center for Wayland, powered by Rust and ConnMan"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
gtk = { package = "gtk4", version = "0.10", features = ["v4_10"] }
gtk4-layer-shell = "0.7.1"
zbus = "5"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
fs2 = "0.4"
async-channel = "2"
async-io = "2"
futures-lite = "2"
signal-hook = "0.3"
gtk4-session-lock = { version = "0.3", features = ["v1_2"] }

[profile.release]
opt-level = 2
strip = true

[[bin]]
name = "nexus"
path = "src/bin/nexus.rs"

[[bin]]
name = "nexusd"
path = "src/bin/nexusd.rs"
