-- Highlight groups of the generated Nexus colorscheme. Nexus prepends the
-- palette table `c` for the current mode and accent.
vim.cmd("highlight clear")
vim.g.colors_name = "nexus"

local function hl(group, spec)
    vim.api.nvim_set_hl(0, group, spec)
end

-- Editor
hl("Normal", { fg = c.fg, bg = c.bg })
hl("NormalNC", { link = "Normal" })
hl("NormalFloat", { fg = c.fg, bg = c.surface })
hl("FloatBorder", { fg = c.border, bg = c.surface })
hl("FloatTitle", { fg = c.accent, bg = c.surface, bold = true })
hl("WinSeparator", { fg = c.border })
hl("Cursor", { fg = c.bg, bg = c.accent })
hl("CursorLine", { bg = c.line })
hl("CursorColumn", { bg = c.line })
hl("ColorColumn", { bg = c.line })
hl("LineNr", { fg = c.faint })
hl("CursorLineNr", { fg = c.accent, bold = true })
hl("SignColumn", { bg = c.bg })
hl("FoldColumn", { fg = c.faint })
hl("Folded", { fg = c.muted, bg = c.line })
hl("Visual", { bg = c.visual })
hl("Search", { fg = c.on_accent, bg = c.accent_bg })
hl("CurSearch", { fg = c.bg, bg = c.yellow })
hl("IncSearch", { link = "CurSearch" })
hl("Substitute", { link = "CurSearch" })
hl("MatchParen", { fg = c.accent, bold = true, underline = true })
hl("NonText", { fg = c.faint })
hl("Whitespace", { fg = c.border })
hl("SpecialKey", { fg = c.faint })
hl("EndOfBuffer", { fg = c.bg })
hl("Pmenu", { fg = c.fg, bg = c.surface })
hl("PmenuSel", { fg = c.on_accent, bg = c.accent_bg })
hl("PmenuSbar", { bg = c.surface })
hl("PmenuThumb", { bg = c.border })
hl("PmenuMatch", { fg = c.accent, bold = true })
hl("WildMenu", { link = "PmenuSel" })
hl("StatusLine", { fg = c.fg, bg = c.surface })
hl("StatusLineNC", { fg = c.muted, bg = c.line })
hl("TabLine", { fg = c.muted, bg = c.surface })
hl("TabLineSel", { fg = c.fg, bg = c.bg, bold = true })
hl("TabLineFill", { bg = c.surface })
hl("WinBar", { fg = c.fg, bold = true })
hl("WinBarNC", { fg = c.muted })
hl("Title", { fg = c.accent, bold = true })
hl("Directory", { fg = c.blue })
hl("ErrorMsg", { fg = c.red })
hl("WarningMsg", { fg = c.yellow })
hl("MoreMsg", { fg = c.green })
hl("Question", { fg = c.green })
hl("ModeMsg", { fg = c.muted })
hl("QuickFixLine", { bg = c.line, bold = true })
hl("SpellBad", { sp = c.red, undercurl = true })
hl("SpellCap", { sp = c.yellow, undercurl = true })
hl("SpellRare", { sp = c.magenta, undercurl = true })
hl("SpellLocal", { sp = c.cyan, undercurl = true })

-- Syntax
hl("Comment", { fg = c.muted, italic = true })
hl("Constant", { fg = c.orange })
hl("String", { fg = c.green })
hl("Character", { link = "String" })
hl("Number", { fg = c.orange })
hl("Boolean", { link = "Number" })
hl("Float", { link = "Number" })
hl("Identifier", { fg = c.fg })
hl("Function", { fg = c.blue })
hl("Statement", { fg = c.accent })
hl("Keyword", { link = "Statement" })
hl("Conditional", { link = "Statement" })
hl("Repeat", { link = "Statement" })
hl("Label", { link = "Statement" })
hl("Exception", { link = "Statement" })
hl("Operator", { fg = c.fg })
hl("PreProc", { fg = c.magenta })
hl("Type", { fg = c.cyan })
hl("Special", { fg = c.magenta })
hl("Delimiter", { fg = c.muted })
hl("Underlined", { underline = true })
hl("Error", { fg = c.red })
hl("Todo", { fg = c.bg, bg = c.yellow, bold = true })

-- Tree-sitter captures that the defaults colour too loudly or not at all
hl("@variable", { fg = c.fg })
hl("@variable.builtin", { fg = c.magenta })
hl("@variable.member", { fg = c.fg })
hl("@property", { fg = c.fg })
hl("@punctuation.bracket", { fg = c.muted })
hl("@punctuation.delimiter", { fg = c.muted })
hl("@tag", { fg = c.accent })
hl("@tag.attribute", { fg = c.cyan })
hl("@tag.delimiter", { fg = c.muted })
hl("@markup.heading", { fg = c.accent, bold = true })
hl("@markup.link.url", { fg = c.blue, underline = true })
hl("@markup.raw", { fg = c.green })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })

-- Diagnostics, diffs and LSP
for name, color in pairs({ Error = c.red, Warn = c.yellow, Info = c.blue, Hint = c.cyan, Ok = c.green }) do
    hl("Diagnostic" .. name, { fg = color })
    hl("DiagnosticUnderline" .. name, { sp = color, undercurl = true })
end
hl("DiffAdd", { bg = c.diff_add })
hl("DiffDelete", { bg = c.diff_delete })
hl("DiffChange", { bg = c.diff_change })
hl("DiffText", { bg = c.diff_text })
hl("Added", { fg = c.green })
hl("Removed", { fg = c.red })
hl("Changed", { fg = c.yellow })
hl("LspReferenceText", { bg = c.line })
hl("LspReferenceRead", { bg = c.line })
hl("LspReferenceWrite", { bg = c.line, underline = true })
hl("LspInlayHint", { fg = c.faint, italic = true })

for i, color in ipairs(c.ansi) do
    vim.g["terminal_color_" .. (i - 1)] = color
end
