//! Colours for applications that do not follow the GTK theme: foot, Neovim
//! and Discord clients (Equibop, Vesktop). They get the Nexus surfaces, the
//! wallpaper accent, and for terminals an ANSI palette tuned for each mode.
use crate::theme::{self, Settings};
use anyhow::Result;
use std::{fs, path::PathBuf, process::Command};

/// The 16 ANSI colours, regular then bright.
fn ansi(dark: bool) -> [&'static str; 16] {
    if dark {
        [
            "#202724", "#e0786d", "#8fc79a", "#e3c27a", "#7fa8d6", "#c69ad6", "#7cc4c0", "#c9d3cd",
            "#6b7772", "#f0948a", "#a9dbb3", "#f0d394", "#9bbfe6", "#d8b3e6", "#9bd8d4", "#edf2ee",
        ]
    } else {
        [
            "#202824", "#b3473b", "#3f7d4c", "#8a6a14", "#3a68a0", "#8a4fa0", "#2f7f7a", "#6f7873",
            "#69736e", "#c75a4d", "#4f9160", "#a07d1c", "#4a7cb8", "#9e62b5", "#3a948e", "#3a423e",
        ]
    }
}
struct Palette {
    dark: bool,
    bg: [f64; 3],
    fg: [f64; 3],
    surface: [f64; 3],
    muted: [f64; 3],
    accent: [f64; 3],
    /// The accent adjusted to read as text on the background.
    accent_fg: [f64; 3],
    on_accent: &'static str,
    ansi: [&'static str; 16],
}
impl Palette {
    fn new(s: &Settings, dark: bool) -> Self {
        let (bg, surface, fg, muted) = theme::palette_for(dark);
        let (bg, accent) = (theme::rgb(bg), theme::rgb(&s.accent));
        Self {
            dark,
            bg,
            fg: theme::rgb(fg),
            surface: theme::rgb(surface),
            muted: theme::rgb(muted),
            accent,
            accent_fg: theme::readable_on(accent, bg),
            on_accent: theme::on_accent(accent),
            ansi: ansi(dark),
        }
    }
    fn ansi_rgb(&self, i: usize) -> [f64; 3] {
        theme::rgb(self.ansi[i])
    }
}
fn plain(c: [f64; 3]) -> String {
    theme::hex(c).trim_start_matches('#').to_string()
}
/// Both foot colour themes, starting in the current mode. Foot switches between
/// them at runtime on SIGUSR1 (dark) and SIGUSR2 (light).
fn foot_ini(s: &Settings) -> String {
    let mut out = format!(
        "# Generated by Nexus from its theme settings; changes are overwritten.\n[main]\ninitial-color-theme={}\n",
        if s.mode == "light" { "light" } else { "dark" }
    );
    for dark in [true, false] {
        let p = Palette::new(s, dark);
        out += &format!(
            "\n[colors-{}]\nbackground={}\nforeground={}\n",
            if dark { "dark" } else { "light" },
            plain(p.bg),
            plain(p.fg)
        );
        for (i, color) in p.ansi.iter().enumerate() {
            let name = if i < 8 { "regular" } else { "bright" };
            out += &format!("{name}{}={}\n", i % 8, color.trim_start_matches('#'));
        }
        out += &format!(
            "cursor={} {}\nselection-foreground={}\nselection-background={}\nurls={}\n",
            plain(p.bg),
            plain(p.accent_fg),
            plain(p.fg),
            plain(theme::mix(p.bg, p.accent, 0.35)),
            plain(p.accent_fg)
        );
    }
    out
}
/// The `nexus` Neovim colorscheme for the current mode.
fn nvim_colors(s: &Settings) -> String {
    let p = Palette::new(s, s.mode != "light");
    let hex = theme::hex;
    let tint = |i: usize, t: f64| hex(theme::mix(p.bg, p.ansi_rgb(i), t));
    let fields = [
        ("bg", hex(p.bg)),
        ("fg", hex(p.fg)),
        ("surface", hex(p.surface)),
        ("line", hex(theme::mix(p.bg, p.fg, 0.05))),
        ("border", hex(theme::mix(p.bg, p.fg, 0.16))),
        ("faint", hex(theme::mix(p.bg, p.fg, 0.32))),
        ("muted", hex(p.muted)),
        ("accent", hex(p.accent_fg)),
        ("accent_bg", hex(p.accent)),
        ("on_accent", p.on_accent.to_string()),
        ("visual", hex(theme::mix(p.bg, p.accent, 0.3))),
        ("red", p.ansi[1].into()),
        ("green", p.ansi[2].into()),
        ("yellow", p.ansi[3].into()),
        ("blue", p.ansi[4].into()),
        ("magenta", p.ansi[5].into()),
        ("cyan", p.ansi[6].into()),
        ("orange", if p.dark { "#e39a6b" } else { "#a95a22" }.into()),
        ("diff_add", tint(2, 0.18)),
        ("diff_delete", tint(1, 0.18)),
        ("diff_change", tint(4, 0.14)),
        ("diff_text", tint(4, 0.3)),
    ];
    let fields: String = fields
        .iter()
        .map(|(k, v)| format!("    {k} = \"{v}\",\n"))
        .collect();
    let ansi: Vec<String> = p.ansi.iter().map(|c| format!("\"{c}\"")).collect();
    format!(
        "-- Generated by Nexus from its theme settings; changes are overwritten.\n\
         -- Clearing the name first keeps the background change from reloading this file.\n\
         vim.g.colors_name = nil\n\
         vim.o.background = \"{}\"\n\
         local c = {{\n{fields}    ansi = {{ {} }},\n}}\n\n{}",
        if p.dark { "dark" } else { "light" },
        ansi.join(", "),
        include_str!("../assets/nvim-colors.lua")
    )
}
pub fn foot_path() -> PathBuf {
    theme::config_dir().join("foot.ini")
}
/// In Neovim's default runtime path, so `:colorscheme nexus` finds it.
pub fn nvim_path() -> PathBuf {
    theme::data_home().join("nvim/site/colors/nexus.lua")
}
fn rgba(c: [f64; 3], alpha: f64) -> String {
    let [r, g, b] = c.map(|v| (v * 255.).round() as u8);
    format!("rgba({r}, {g}, {b}, {alpha})")
}
/// Maintained Discord theme whose colour variables are meant to be overridden;
/// it follows Discord's frequent class and variable changes.
const DISCORD_BASE: &str = "https://refact0r.github.io/midnight-discord/build/midnight.css";
/// Discord colours for the current mode, as overrides of the base theme.
fn discord_css(s: &Settings) -> String {
    let p = Palette::new(s, s.mode != "light");
    let hex = theme::hex;
    let vars = [
        ("text-0", p.on_accent.to_string()),
        ("text-1", hex(p.fg)),
        ("text-2", hex(p.fg)),
        ("text-3", hex(theme::mix(p.fg, p.bg, 0.12))),
        ("text-4", hex(p.muted)),
        ("text-5", hex(theme::mix(p.muted, p.bg, 0.45))),
        ("bg-1", hex(theme::mix(p.surface, p.fg, 0.08))),
        ("bg-2", hex(theme::mix(p.surface, p.fg, 0.04))),
        ("bg-3", hex(p.surface)),
        ("bg-4", hex(p.bg)),
        ("hover", rgba(p.fg, 0.06)),
        ("active", rgba(p.fg, 0.1)),
        ("active-2", rgba(p.fg, 0.14)),
        (
            "message-hover",
            rgba([0.; 3], if p.dark { 0.1 } else { 0.03 }),
        ),
        ("button-border", rgba(p.fg, 0.1)),
        ("accent-1", hex(p.accent_fg)),
        ("accent-2", hex(p.accent)),
        ("accent-3", hex(p.accent)),
        ("accent-4", hex(theme::mix(p.accent, p.fg, 0.1))),
        ("accent-5", hex(theme::mix(p.accent, p.fg, 0.2))),
    ];
    let vars: String = vars
        .iter()
        .map(|(k, v)| format!("    --{k}: {v};\n"))
        .collect();
    format!("@import url(\"{DISCORD_BASE}\");\n:root {{\n{vars}}}\n")
}
/// QuickCSS files of the Discord clients that are installed. They reload them
/// as soon as they change.
fn discord_paths() -> Vec<PathBuf> {
    let config = theme::config_dir()
        .parent()
        .map(PathBuf::from)
        .unwrap_or_default();
    ["equibop", "vesktop"]
        .iter()
        .map(|app| config.join(app))
        .filter(|dir| dir.is_dir())
        .map(|dir| dir.join("settings/quickCss.css"))
        .collect()
}
pub fn write(s: &Settings) -> Result<()> {
    theme::write_atomic(&foot_path(), &foot_ini(s))?;
    theme::write_atomic(&nvim_path(), &nvim_colors(s))?;
    let css = discord_css(s);
    for path in discord_paths() {
        // The user's own QuickCSS stays around the block; the @import must lead.
        // Written in place: the clients watch the file itself, and replacing it
        // would end their watch after the first change.
        let text = fs::read_to_string(&path).unwrap_or_default();
        fs::write(&path, theme::replace_block(&text, &css, true))?;
    }
    Ok(())
}
/// Switches running foot windows to the theme of the new mode; new windows
/// read it from foot.ini. Neovim reloads the colorscheme file on its own.
pub fn signal_foot(dark: bool) {
    let _ = Command::new("pkill")
        .args([
            if dark { "-USR1" } else { "-USR2" },
            "-u",
            &std::env::var("USER").unwrap_or_default(),
            "-x",
            "foot",
        ])
        .status();
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn foot_has_both_themes() {
        let ini = foot_ini(&Settings::default());
        assert!(ini.contains("initial-color-theme=dark"));
        assert!(ini.contains("[colors-dark]\nbackground=151a18\n"));
        assert!(ini.contains("[colors-light]\nbackground=f3f4f0\n"));
        assert_eq!(ini.matches("bright7=").count(), 2);
        assert!(!ini.contains("=#"));
    }
    #[test]
    fn discord_import_comes_first() {
        let css = discord_css(&Settings::default());
        assert!(css.starts_with("@import url("));
        assert!(css.contains("--bg-4: #151a18;"));
        assert!(css.contains("--hover: rgba(237, 242, 238, 0.06);"));
    }
    #[test]
    fn nvim_colors_follow_the_mode() {
        let light = Settings {
            mode: "light".into(),
            ..Settings::default()
        };
        let lua = nvim_colors(&light);
        assert!(lua.contains("vim.o.background = \"light\""));
        assert!(lua.contains("bg = \"#f3f4f0\""));
        assert!(lua.contains("hl(\"Normal\""));
    }
}
